### ISSUE TITLE
Raw Data and Summary Statistics Problem

### ISSUE THREAD

**Issue by hopkin28** [egonet/egonet#10]
After completing an interview we can reopen the interviews under view interview in the interview and analysis tool, but the raw data and summary statistics features aren't working.  When we use the Raw data feature, which saves as a csv, we get an error and the csv is blank. The same happens with the summary statistics feature. 

Any thoughts on what might be going on?

Thanks,
Allison

**Comment by martinb3** [comment]
Hi @hopkin28 -- could you share the error you're getting?

**Comment by hopkin28** [comment]
Absolutely, I included a word document with screen shots and info/questions to clarify the issue.

[Raw Data Issue.docx](https://github.com/egonet/egonet/files/121973/Raw.Data.Issue.docx)

**Comment by ahowerter** [comment]
Here are some additional screenshots of the error.  I'm @hopkin28 colleague on the study
[Additional details.docx](https://github.com/egonet/egonet/files/122063/Additional.details.docx)

**Comment by martinb3** [comment]
Hi @hopkin28 and @ahowerter -- looking at your first document:

> Are these the files that are created from the raw data and summary statistics options? If so, than the issue I brought up is a non-issue. 

I think the answer is yes. The statistics and raw buttons don't let you pick a file -- they generate multiple files so they only let you pick a directory.

Looking through your 2nd document --

The "Error that did not include a detailed explanation" appears to be an issue with the way Java is configured on your computer. It looks like it's being blocked by some security rules.

The warning about "No questions with specified adjacency" is usually due to an alter-pair / alter tie question with multiple choice answers, where the answer needs to be marked "adjacent" that is intended to be used for the actual presence of a link or tie in the network (and thus, adjacent in the matrix).

I hope this helps!

- Martin

**Comment by ahowerter** [comment]
Hi @martinb3 
I did in fact have a Java conflict on my computer.  I was able to resolve the issue after reinstalling Java.
Thanks for the help!

**Comment by martinb3** [comment]
Great! Thank you for following up.
